### PR TITLE
First pass at the outline

### LINKED ISSUE #2: What are our six sections of the day?
Here's my stab at one way we might break up the 2 hours. What do you think?
- Part One
  - iPython interpreter/notebook
  - pandas
    - What is a series? What is a dataframe?
    - How do I read in data?
    - How can I clean data?
  - A hands-on exercise
- Part Two
  - pandas
    - More cleaning and transposing of tables
    - aggregating, groupbys, sorting
  - plotting your data in simple bar charts, line graphs and scatter plots
  - More hands-on exercise

### PR DESCRIPTION
**Pull request by tswicegood**
@tommeagher thoughts?

Closes #2.

### CODE REVIEW

**Comment by tswicegood** [comment]
FYI -- you can render this locally with `jekyll serve`.  I have the `gh-pages` branch already set up and viewable here: http://tswicegood.github.io/python-data-science-intro/.

Not sure if you want to go with slides or with something more narrative?  I kinda like the idea of narrative and then we use it as our notes for actually going through and doing a live demo throughout.  Thoughts?

**Comment by tswicegood** [comment]
Also, I'm not wedded to the idea of it having to be a full-blown site like this.  We could swap out to something like Reveal and go the more traditional slide route too.

**Comment by tommeagher** [comment]
Travis, this is fantastic, and way better than what I had in mind. I figured we'd just have a couple of iPython notebooks. So do you envision each of these 4 sections being a blog post with code snippets in it? How do you see the hands-on sections working? 
I think I see where you're going with this, and I'm on board. Do you want to do sections 1 (conda) and 4 (bokeh) and I'll do 2 (import csv/excel and browse through a dataframe) and 3 (cleaning data, transposing, slicing)? If so, I'd say go ahead and merge this branch and close #4 and #2. 
I've got some time blocked out Sunday night and Monday night to roll through this.

Thanks, Tom

**Comment by tswicegood** [comment]
Awesome!  Glad you like this direction.  I've got the start to my intro in place.  I'll open up a PR with it shortly and so you can see where I'm going.  Feel free to add in some ipynb files too, but I like the idea of having students type this out rather than giving them pre-baked solutions.  Learning isn't a spectator's sport. :-)

**Comment by tommeagher** [comment]
Totally agree. The more we can have them typing code themselves (in the iPython Notebook, of course), the better.

**Pull request merged**
