### PR TITLE
Part2

### PR DESCRIPTION
**Pull request by tommeagher**
I created pages for parts 2 and 3. The part 2 page, "Pandas, the First Look," can be tweaked and the wording improved, but it covers the bases. I'm open to suggestions on other concepts to include (vectorizing functions?). 
For part 3, which is the "Pandas, Digging Deeper," it's just an outline of what I plan to tackle in that. 

Let me know if this is along the lines of what you had in mind. If so, I'll keep charging ahead.

Thanks!

### CODE REVIEW

**Comment by tommeagher** [comment]
Also added a short intro section on why to use this stack instead of Excel or R.
Working on finishing roughing out the "Digging Deeper" section, which I hope to push tonight, then will go back and rewrite and smooth out the bumpy parts.

**Comment by tommeagher** [comment]
Added the code steps for part 3. Heading to the airport in a few hours and plan to spend the flight rewriting and fleshing out the explanations. Let me know if you have any questions or if anything doesn't work, otherwise I'll keep charging ahead.

**Comment by tswicegood** [comment]
So far everything's looking awesome. Do you want to block out an hour or so tomorrow to go thru everything and make sure it all gels together?

**Comment by tommeagher** [comment]
We should definitely meet up. I'm teaching a class all-day tomorrow. We could chat at the end of the day, or some time on Friday.

**Pull request merged**
