### PR TITLE
Tools Section

### PR DESCRIPTION
**Pull request by tswicegood**

### CODE REVIEW

**Comment by tswicegood** [comment]
@tommeagher this is what I was thinking for each section.  Going to go ahead and merge this, but I wanted to open a PR so you could see where I was headed.

**Comment by tommeagher** [comment]
Beautiful. This is helpful. And I'll send a pull request tonight with a pass at the two Pandas sections.

**Comment by tswicegood** [comment]
@tommeagher awesome!  I was playing with that data set over the weekend trying to think of interesting visualizations.  My thought process was something like:
- show the tools
- pull in pandas/numpy
- show cleaning up data (frigging leading spaces in the columns?!)
- show aggregating data / asking questions
- show visualizing data to get more context

If we build a continual process, we should have a nice notebook with data at the end of it that's got visualizations.  Do you have any idea what data you're going to have at the end?

---

Also, it'd be great to do lead-ins from one section to the next.  If you want to write a "Next Steps…" section for tools, go for it.

**Comment by tommeagher** [comment]
This is pretty much the outline I had in mind. As far as what the data will look like at the end, I'm not sure yet, but will know tonight. What kind of charts do you want to do?

**Comment by tswicegood** [comment]
Well, we have time series data so an obvious one is a scatter plot of deaths by month, death by day of week, and so on.  With bokeh I can add controls the charts so we can re-render based on selection.  If there's anything you get out of it while working with the data, let me know and I can work around that.

**Comment by tommeagher** [comment]
If we have time, it'd be good to do a bar chart, a line graph, a histogram and a scatterplot. Let me dig in this evening and I'll have a better proposal for what data to funnel into those charts.

**Comment by tswicegood** [comment]
Based on what I saw, maybe this:
- Deaths by county (bar)
- Accidents over time (line)
- Number of people involved (was that in there?  I think so) over time (histogram)
- Number of people involved by day (scatter)

I'll work up examples for each that we can plug data into once you've got the list solidified.

**Comment by tommeagher** [comment]
Cool. For the latter two, we can look at these cols:
`Total Killed, Total Injured, Pedestrians Killed, Pedestrians Injured,`

**Pull request merged**
